### PR TITLE
Apple.com clone  project on HTML

### PR DESCRIPTION
**Pull request by Abdoulaye-Thespy**
I this milestone, I cloned Apple.com old version  using HTML and CSS.

CSS Errors were fixed locally since I am having trouble with Stickler app.

### CODE REVIEW

**Comment by adaorachi** [comment]
👋 Hi @Abdoulaye-Thespy,

Well done on the completion of the first draft of your project. There are a couple of things you'll need to fix to make your project look very professional and just like the original site.

---
CHANGES REQUIRED
---

First, your front banner and navigation bar has a couple of issues.

- [ ] You used `<input>` tags for all the navigation list. This is **not a right practice!**. Ensure you use the `<li>` tag here. You are only allowed to use the `<input>` tag for the search bar.

- [ ] You should also ensure that your navbar uses a gradient background; for that is the main purpose of this project. Also, apply hover effects to the links.

- [ ] Ensure that your banner image is properly centered and should cover the whole page irrespective of the screen size. Use the background-size and positioning CSS properties.

- [ ] You have your title text as images, kindly remove them and instead generate them using HTML codes and tags. 

- [ ] The whole site page of your project is not properly fitted and aligned. There are white spaces trailing down the entire page. Your page should not have the scrolling bar highlighted in the screenshot below. Kindly get that fixed.

Kindly make reference to the original site and fix these issues.

**Image:**

apple11

----

- [ ] The four images below are not properly aligned. Make sure each image is in its own container `<div>` tag and also ensure the images are generated separately. You have the four images generated with a single `background` CSS selector. This is **not a right practice!**. Kindly make reference to the original site and fix this.

- [ ] Your footer content does not look similar to that of the original site. Ensure you use the right colors and font-sizes to get them fixed.

**Image:**

apple2

---
### **Kindly implement the changes highlighted above and request for another review when you are done with them by submitting another code review form.**
---

Should you have any question or need any help, feel free to reach me on Slack with the username (@adaorachi)

Good luck in it and happy coding ☺️ 

**MaryAnn Chukwuka**

**Comment by mikenath223** [comment]
**Pull request currently under review by Michgolden Ukeje (TSE).**
Kindly exercise patience 👋

**Review by mikenath223 — CHANGES_REQUESTED** [review]
Hi @Abdoulaye-Thespy  👋

You've obviously worked quite hard at this.👍

Project looks quite ok but there are a few changes to be made:👇

- [ ] Required -  Kindly fix the linting issue in the CSS file.

- [ ] Required - There are a few adjustments to be made on your navbar.
ice_screenshot_20200408-121313

* Kindly ensure you have no spaces in between the navbar items, just as it looks on the original and center all text in each nav item.

* Also please ensure that the search input is actually a search input field.
ice_screenshot_20200408-121225

* And kindly add a border-radius to the navbar.

- [ ] Required - Kindly increase the font-sizes of the following sections shown below.
THE MID TEXT SECTION👇
ice_screenshot_20200408-121239

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by thsvr** [comment]
### **STATUS: PROJECT APPROVED** :100: :1st_place_medal: :100: 

Hi @Abdoulaye-Thespy :smile: :smile: 

Congratulation for the hard work, **you did a great job** :1st_place_medal:  and implemented all the required changes asked by Mike and MaryAnn, so your project was approved :fireworks: :fireworks: :fireworks: :fireworks: 

:v: Before merging it to master and go ahead with the next project, can you please update the live version to show a hyperlink? In your readme it is showing a link that is not working yet. The way to do it is just as the usual :
`<a href="">Live version</a>`




If you have any questions, don't hesitate to contact me through slack [@thaís Vieira Azevedo](url)


### **Happy coding and good luck on the next project** :computer: 

_Project reviewed by Thaís Vieira (TSE)_

**Pull request merged**
